; CGA
; White: 255
; Magenta: 164
; Cyan: 43

[Theme-256]
name: CGA Days
mainColor: 43
clickColor: 164
clickHighlightColor: 255
borderColor: 43
notificationColor: 30
promptColor: 164
menuItemColor: 43
menuTitleColor: 255
menuBorderColor: 164

