; CGA
; White: 255
; Bright Red: 203
; Cyan: 51

[Theme-256]
name: CGA Nights
mainColor: 203
clickColor: 51
clickHighlightColor: 255
borderColor: 203
notificationColor: 51
promptColor: 51
menuItemColor: 51
menuTitleColor: 255
menuBorderColor: 203

