; colors for 16-color mode:
; 1 black
; 2 blue
; 3 green
; 4 cyan
; 5 red
; 6 magenta
; 7 yellow
; 8 white

[Theme-16]
name: CGA Dayz
mainColor: 4
clickColor: 6
borderColor: 4
clickHighlightColor: 7
notificationColor: 4
promptColor: 4
menuItemColor: 4
menuTitleColor: 6
menuBorderColor: 6

