; purple: 55
; darkish red: 160, another red: 197
; laser green: 41
; blue: 21

[Theme-256]
name: Laser Tag
mainColor: 240
clickColor: 197
clickHighlightColor: 255
borderColor: 238
notificationColor: 41
promptColor: 41
menuItemColor: 250
menuTitleColor: 41
menuBorderColor: 239

