; hot pink: 201, mid grey: 242, bright cyan: 51, dark grey: 235,
; electric blue (dull cyan): 75, neon teal: 45, soft white: 252
; magenta: 165, light grey: 236

[Theme-256]
name: Night Drive
mainColor: 242
clickColor: 201
clickHighlightColor: 51
borderColor: 235
notificationColor: 75
promptColor: 45
menuItemColor: 252
menuTitleColor: 75
menuBorderColor: 236

