; pink: 162, space green: 35, night cyan: 30, dark blue: 19, darker blue: 18
; star: 228, rusty orange: 172, dark rusty: 95, dark rusty orange: 94

[Theme-256]
name: Orbit
mainColor: 30
clickColor: 228
clickHighlightColor: 228
borderColor: 18
notificationColor: 30
promptColor: 35
menuItemColor: 30
menuTitleColor: 228
menuBorderColor: 35

