; Outrunnable
; purple: 93, hot pink: 197, yellow: 220, gray? 242, cyan: 39

[Theme-256]
name: Outrunnable
mainColor: 197
clickColor: 39
clickHighlightColor: 51
borderColor: 93
notificationColor: 75
promptColor: 45
menuItemColor: 252
menuTitleColor: 220
menuBorderColor: 197

