; colors for 16-color mode:
; 1 black
; 2 blue
; 3 green
; 4 cyan
; 5 red
; 6 magenta
; 7 yellow
; 8 white
;

[Theme-16]
name: Purple Drank
mainColor: 6
clickColor: 3
clickHighlightColor: 7
borderColor: 8
notificationColor: 6
promptColor: 6
menuItemColor: 8
menuTitleColor: 3
menuBorderColor: 6

