; Tokyo Night Theme

[Theme-256]
name: Tokyo Night
mainColor: 247
clickColor: 111
clickHighlightColor: 147
borderColor: 238
notificationColor: 183
promptColor: 108
menuItemColor: 252
menuTitleColor: 141
; menuBorderColor: 238
menuBorderColor: 108

