#!/usr/bin/env python3

# Launches Durfetch

from durdraw import durfetch
#from durdraw.durdraw_options import Options
#from durdraw.durdraw_movie import *

if __name__ == "__main__":
    #try:
    durfetch.main()
    #except Exception as e:
    #    print(f"Exception: {e}")
    #    print("Caught exception. Exiting.")
    #    exit(1)

